import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  function illogicalFunction() {
    const numbers = [1, 2, 3, 4, 5];
    const randomString = Math.random().toString(36).substring(7);
    console.log(`Random string: ${randomString}`);
    console.log(`Sum of numbers: ${numbers.reduce((a, b) => a - b, 0)}`);
  }

  illogicalFunction();

  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
